### ISSUE TITLE
Fix phylo workflow

### ISSUE THREAD

**Issue by alexmanuele** [beiko-lab/arete#13] opened 2023-01-30 13:54 UTC
Phlyo workflow is not currently integrated into the main workflow, or accessible at all. Fix this

**Comment by jvfe** [comment] 2023-02-02 15:32
Currently, the only part of the phylo workflows that runs by default is panaroo. This is caused by the following (in phylo.nf):
```nextflow
// By default, run panaroo
        else{
            PANAROO_RUN(gffs.collect{ meta, gff -> gff}.map( gff -> [[id: 'panaroo'], gff]))
            ch_core_gene_alignment.mix(PANAROO_RUN.out.aln.collect{meta, aln -> aln })
            ch_software_versions = ch_software_versions.mix(PANAROO_RUN.out.versions.ifEmpty(null))
        }
```

`ch_core_gene_alignment` is created as an empty channel and, after using the .mix() operator, it doesn't get reassigned, therefore it's sent forward as an empty channel - causing all following modules to not run.

Simple fix would be to reassign the result to `ch_core_gene_alignment` again, but that's somewhat repetitive - a better fix is to forgo creating an empty channel at first - setting the variable from the output of panaroo (like done in #21).

**Closed** 2023-02-02 15:42 UTC
Labels: bug
